Respected Mam,
This email is to notify you that I am resigning from my position here as Sr. Technical Lead, effective today i.e. 18th April 2022.
Thank you for all the opportunities you have provided me over the years. I have enjoyed my time working for this company and have learned so much. I am also grateful for your kindness and encouragement as well as the kindness of my colleagues.

Over the next 2 months, I will complete all my projects and make myself available to train a replacement for my duties. Please let me know if I can do anything to help make this transition easier. In the future, you can always contact me on my non-work email, manikgarg@yahoo.com.

Sincerely,
Manik Garg
